"""Second migration

Revision ID: d09781c41c10
Revises: 71db90348325
Create Date: 2025-05-29 21:48:16.019248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09781c41c10'
down_revision = '71db90348325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
